### ISSUE TITLE
OSRM run with local docker container

### ISSUE THREAD

**Issue by syounkin** [bvarick/route_analysis#2]
Ben,

I thought I would turn my questions about osrm into an issue on Github. I have lots of questions about the docker container setup. Maybe here is a good place to sort them out?

Thanks,

Sam

**Comment by bvarick** [comment]
Hey Sam, 
I run the docker container on the same computer I'm running the script on, it just needs to have [the docker engine](https://docs.docker.com/engine/install/) installed on it. You could run it on a separate machine either on your LAN or available over the WAN. Doing it on the same machine improves the latency.

Here's a step by step of what I did: (these are very similar to [OSRM's documentation](https://hub.docker.com/r/osrm/osrm-backend))

1. Download the relevant OpenStreetMap (OSM) data. I downloaded all of Wisconsin (the .osm.pbf file) from here: https://download.geofabrik.de/north-america/us.html
    a. I saved the OpenStreetmap data in the folder `/home/ben/docker/osrm/data`. Change that part of the following commands to wherever you saved it. This file is ~262MB.


3. I prepossessed the data, with these commands. You only need to do this once (or whenever you update the underlying OSM data). This generates ~2.2GB of files for Wisconsin.
    a. `docker run -t -v "/home/ben/docker/osrm/data:/data" osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/wisconsin-latest.osm.pbf`
    b. `docker run -t -v "/home/ben/docker/osrm/data:/data" osrm/osrm-backend osrm-partition /data/wisconsin-latest.osrm`
    c. `docker run -t -v "/home/ben/docker/osrm/data:/data" osrm/osrm-backend osrm-customize /data/wisconsin-latest.osrm`


4. Then I spin up a couple of docker containers with the following docker-compose.yml file:
```
---
services:
    osrm-backend:
        ports:
            - 5000:5000
        volumes:
            - /home/ben/docker/osrm/data:/data
        image: osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/wisconsin-latest.osrm
    osrm-frontend:
        ports:
            - 9966:9966
        image: osrm/osrm-frontend
```

  a. I saved that file as docker-compose.yml which defines the containers. Then I start the containers by running `docker compose up -d`


5. now I can access a webgui at http://127.0.0.1:9966 to visualize individual routes (and double check that everything is working). And I can query the routing engine through its API at http://127.0.0.1:5000/ within the R script.

**Comment by syounkin** [comment]
Thank you for the detailed instructions. I will work my way through them today.

**Comment by syounkin** [comment]
I have now run _route_analysis.Rmd_ without error. Thanks for these instructions. They were very helpful.

**Comment by bvarick** [comment]
I think we need to make some adjustments for bicycling. I think that OSRM can only be set up to do one mode of travel in the preprocessing step (defined by the `/opt/foot.lua`) per instance. We can set up a seperate backend for cycling in a seperate docker container, with a seperate data directory and expose it on port 5001 for cycling. And then query backend at port 5000 for walking and 5001 for cycling. Or we could assume (especially for kids), that they bike where they would walk, so walking directions are fine for cycling.

**Comment by bvarick** [comment]
So I got something up and running. I made three subdirectories in my docker directory: 
- `data-raw`: where the raw wisconsin-latest.osm.pbf lives
- `data-foot`: where the preprocessed walk routing data lives
- `data-bicycle`: where the preprocessed bicycling routing data lives

These are my pre-processing commands
### pre-processing for walking
```
docker run -t \
-v "./data-foot:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-extract -p /opt/foot.lua /data/wisconsin-latest.osm.pbf
```
```
docker run -t \
-v "./data-foot:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-partition /data/wisconsin-latest.osrm
```
```
docker run -t \
-v "./data-foot:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-customize /data/wisconsin-latest.osrm
```
### pre-processing for bicycling
```
docker run -t \
-v "./data-bicycle:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-extract -p /opt/bicycle.lua /data/wisconsin-latest.osm.pbf
```
```
docker run -t \
-v "./data-bicycle:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-partition /data/wisconsin-latest.osrm
```
```
docker run -t \
-v "./data-bicycle:/data" \
-v "./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf" \
osrm/osrm-backend \
osrm-customize /data/wisconsin-latest.osrm
```
### docker-compose.yml
And this is the `docker-compose.yml` that creates two containers, one accessing the foot routing data exposed on port 5000, one accessing the bicycle routing data exposed on port 5001.
```
---
services:
    osrm-backend-foot:
        container_name: osrm-backend-foot
        ports:
            - 5000:5000
        volumes:
            - ./data-foot:/data
            - ./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf
        image: osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/wisconsin-latest.osrm
    osrm-backend-bicycle:
        container_name: osrm-backend-bicycle
        ports:
            - 5001:5000
        volumes:
            - ./data-bicycle:/data
            - ./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf
        image: osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/wisconsin-latest.osrm

```

**Comment by bvarick** [comment]
Here's a docker-compose.yml with frontends to compare the walking and bicycling routes:
```
---
services:
    osrm-backend-foot:
        container_name: osrm-backend-foot
        ports:
            - 5000:5000
        volumes:
            - ./data-foot:/data
            - ./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf
        image: osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/wisconsin-latest.osrm
    osrm-backend-bicycle:
        container_name: osrm-backend-bicycle
        ports:
            - 5001:5000
        volumes:
            - ./data-bicycle:/data
            - ./data-raw/wisconsin-latest.osm.pbf:/data/wisconsin-latest.osm.pbf
        image: osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/wisconsin-latest.osrm
    osrm-frontend-foot:
        ports:
            - 9966:9966
        environment:
            OSRM_BACKEND: 'http://localhost:5000'
        image: osrm/osrm-frontend
    osrm-frontend-bicycle:
        ports:
            - 9967:9966
        environment:
            OSRM_BACKEND: 'http://localhost:5001'
        image: osrm/osrm-frontend

```
Walking frontend: http://127.0.0.1:9966/
Biking frontend: http://127.0.0.1:9967/
